### ISSUE TITLE
return overindented for multiple arguments

### ISSUE THREAD

**Issue by glvnst** [TomasTomecek/download-manifest-from-dockerhub#2]
https://github.com/TomasTomecek/download-manifest-from-dockerhub/blob/76f19acb6aa8be313834b74431e318c6e075ab8f/download-manifest.py#L50

Nice work! Thanks for sharing this. I'm using a [fork of your script](https://github.com/glvnst/conex/blob/master/.helpers/dhmanifest.py) for some CI/CD stuff.

I noticed one minor thing: I think you intended the above return statement to be "out-dented" by one level to allow for multiple repotag arguments.

**Comment by TomasTomecek** [comment]
Oh yeah, nice catch! Feel free to send a PR.

**Comment by glvnst** [comment]
thanks again
